spring:
  profiles:
    active: 
      - dog
      - EN
      - prod
guru:
  username: YMLUsername
  password: YMLPassword
  jdbcurl: YMLJDBCUrl    
guruguru:
  username: YMLUsernameGURUGURU
  password: YMLPasswordGURUGURU
  jdbcurl: YMLJDBCUrlGURUGURU
---
spring:
  profiles: prod
guru:
  username: YMLUsernameProd
  password: YMLPasswordProd
  jdbcurl: YMLJDBCUrlProd